### ISSUE TITLE
[0.3.6] brightness, sleepmode and alert screens not working

### ISSUE THREAD

**Issue by hamster65** [o0shojo0o/node-red-contrib-pixelit#2]
Hi,
I updated the node and now I see the following:

- brightness adjustment does not work, I think it stays at the default brightness level.
- when I inject sleepmode_on, the it does not go dark. It just stops and shows a still image (or at least it does not go to the next screen). In continues when I inject sleepmode_off.
- My alertscreen, which scrolls a text, sometimes freezes. Sometimes it goes blank but a few pixels of the text stay on.

I restarted node-red, rebooted the pi and re-deployd the whole workspace.... no luck.

**Comment by o0shojo0o** [comment]
> Hi,
> I updated the node and now I see the following:
> 
> * brightness adjustment does not work, I think it stays at the default brightness level.
> * when I inject sleepmode_on, the it does not go dark. It just stops and shows a still image (or at least it does not go to the next screen). In continues when I inject sleepmode_off.

Hi the issues are fixed in the next version I am about to release. 

> * My alertscreen, which scrolls a text, sometimes freezes. Sometimes it goes blank but a few pixels of the text stay on.

This indicates that your PixelIt hangs, because the Node-Red part only generates a JSON which the PixelIt interprets and processes. 
A too weak power supply or a missing capacitor could be the problem.

**Comment by hamster65** [comment]
Hi,
thanks! I just figured out that the blank screen with the pixels on it was the result of a long string with html in it. It was generated by a weather warning flow. The idea was to output a warning as scrolling text, which never showed up / worked before.

**Comment by hamster65** [comment]
Hi, I updated to 0.3.7. Brightness and sleep works fine again, scrolling works wenn set to "auto". Thanks for fixing it!
Scrolling does not work when set to "on", it displays a static text then. I am fine with the auto setting :)
