### ISSUE TITLE
Next screen function

### ISSUE THREAD

**Issue by foorschtbar** [o0shojo0o/node-red-contrib-pixelit#4]
Is a "go to next screen in playlist" function possible? When i test something and have a long playlist, in need to wait until the new screen appears...

**Comment by o0shojo0o** [comment]
Yes this is possible, if you set a screen init node with 0 duration and send it on the alert node. 
![image](https://user-images.githubusercontent.com/19333515/119717274-6081e800-be66-11eb-9a3f-3574f53ac3d6.png)

**Comment by foorschtbar** [comment]
![grafik](https://user-images.githubusercontent.com/10727275/119778482-e2562d80-bec7-11eb-8413-da9fa674ae38.png)

Works for me. Thank u!
